server:
  ip: 47.113.199.13
  port: 9090

spring:
    datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://47.113.199.13:3306/fruitdb?useUnicode=true&characterEncoding=utf8&useSSL=false
     username: root
     password: root
#     //服务器和本地的密码不同需要改一下，服务器密码是root

#这是让mapper文件在没有找到手写的注解时2能找到xml的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: /home/files

    #這裏一定要寫/home/files/ 不能只寫home/files 否則會找不到
